<<<<<<< HEAD
# Copied on 2014-01-06 from https://github.com/craigcitro/r-travis; validate this file at http://lint.travis-ci.org/
# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs
=======
# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
bioc_required: true

env:
 global:
   - CRAN: http://cran.rstudio.com
   - WARNINGS_ARE_ERRORS=1
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran
   
r_github_packages:
  - Rexamine/stringi

r_packages:
  - rjags
>>>>>>> development

notifications:
  email:
    on_success: change
    on_failure: change
